version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1050
      POSTGRES_DB: sharksport
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
