
FROM python:3.10-slim



WORKDIR /app



RUN apt-get update && apt-get install -y libpq-dev gcc



COPY requirements.txt .



RUN pip install --no-cache-dir -r requirements.txt



COPY . .



EXPOSE 8000
EXPOSE 5432



WORKDIR /app/app



CMD ["uvicorn", "config:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
