
FROM python:3.10-alpine



WORKDIR /app



RUN apt-get update && apt-get install -y libpq-dev gcc



COPY requirements.txt .



RUN pip install --no-cache-dir -r requirements.txt



COPY . .


EXPOSE 8000
EXPOSE 5432

WORKDIR /app/app


CMD ["python","main.py"]
