services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1050
      POSTGRES_DB: sharksport
    ports:
      - "5432:5432"
    restart: always

  web:
    image: rezamoridi/sharksport:latest
    command: ["uvicorn", "config:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
